{% set name = "pysipfenn" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysipfenn-{{ version }}.tar.gz
  sha256: ffe1c8e773d147a98353d456566834a966c6d3fac8c02f95d2e62e45f75c3b71

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - pymatgen >=2022.1.9
    - pytorch >=1.11.0
    - onnx2torch >=1.5.2
    - onnx >=1.9.0
    - python-wget >=3.2
    - numpy >=1.22.0
    - tqdm >=4.63.0
    - natsort >=8.0.0
    - pymongo >=4.2
    - pysmartdl >=1.3.4
    - dnspython

test:
  imports:
    - pysipfenn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://phaseslab.com/sipfenn
  summary: Easily extensible Python package for running Structure-Informed Prediction of Formation Energy using Neural Networks (SIPFENN)
  license: GPL-3.0-or-later
  license_file: LICENSE.md
  dev_url: https://github.com/PhasesResearchLab/pySIPFENN

extra:
  recipe-maintainers:
    - amkrajewski
    - jan-janssen
