{% set name = "pysipfenn" %}
{% set version = "0.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysipfenn-{{ version }}.tar.gz
  sha256: 450a9b734ea11c64e9b27aec4348155267f84175371edc2d1184d5126bd97342

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - setuptools-scm
    - pip
  run:
    - plotly >=5.15.0
    - colorama
    - pysmartdl2 >=2.0.0
    - ruamel.yaml
    - spglib ==2.0.2
    - python >=3.9
    - pymatgen >=2024.2.20
    - pytorch >=2.1.0
    - onnx2torch >=1.5.2
    - onnx >=1.13.0
    - numpy >=1.25.0,<2.0.0
    - tqdm >=4.65.0
    - natsort >=8.3.0
    - pymongo >=4.4
    - pysmartdl >=1.3.4
    - dnspython

test:
  imports:
    - pysipfenn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://phaseslab.com/sipfenn
  summary: Easily extensible Python package for featurizing periodic atomic structures and running Structure-Informed Prediction of Formation Energy using Neural Networks (SIPFENN)
  license: LGPL-3.0-only
  license_file: LICENSE.md
  dev_url: https://github.com/PhasesResearchLab/pySIPFENN

extra:
  recipe-maintainers:
    - amkrajewski
    - jan-janssen
