{% set name = "pysipfenn" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysipfenn-{{ version }}.tar.gz
  sha256: 3ad92041c45d66cdf912205aabb6ce302024511877652256a43c67ce365335d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - pymatgen >=2023.2.22
    - pytorch >=1.11.0
    - onnx2torch >=1.5.2
    - onnx >=1.13.0
    - numpy >=1.22.0
    - tqdm >=4.65.0
    - natsort >=8.3.0
    - pymongo >=4.2
    - pysmartdl >=1.3.4
    - dnspython

test:
  imports:
    - pysipfenn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://phaseslab.com/sipfenn
  summary: Easily extensible Python package for featurizing periodic atomic structures and running Structure-Informed Prediction of Formation Energy using Neural Networks (SIPFENN)
  license: LGPL-3.0-only
  license_file: LICENSE.md
  dev_url: https://github.com/PhasesResearchLab/pySIPFENN

extra:
  recipe-maintainers:
    - amkrajewski
    - jan-janssen
